title: 田平安's Homepage
page-top-title: 田平安
top-section-bg-text: AI Agent & AI Application
home-subtitle: 田平安&ensp;|&ensp;AI Agent / AI 应用开发
copyright-text: '&copy; 田平安 2024-2026. All Rights Reserved.'
